default: (run-game-set "./acards.txt" "./bcards.txt")

setup:
    meson setup build

[working-directory: 'build']
build:
    ninja

run-game-set +FILES: build
    ./build/game_set {{FILES}}

run-game +FILES: build
    ./build/game {{FILES}}

test: build
    meson test -C build


all: build

clean:
    rm -rf build

reconfigure:
    meson setup --reconfigure build

help:
    just --list
