default: (run-game-set "../acards.txt" "../bcards.txt")

setup:
    meson setup build

[working-directory: 'build']
build:
    ninja

[working-directory: 'build']
run-game-set +FILES: build
    ./game_set {{FILES}}

[working-directory: 'build']
run-game +FILES: build
    ./game {{FILES}}

test: build
    echo "+++ Running tests..."
    meson test -C build


all: build

clean:
    rm -rf build

reconfigure:
    meson setup --reconfigure build

help:
    just --list
