on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    tags:
      - v?[0-9]+.[0-9]+.[0-9]+*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  DeterminateCI:
    uses: DeterminateSystems/ci/.github/workflows/workflow.yml@main
    with:
      runner-map: |
        {
          "aarch64-darwin": "macos-latest",
          "x86_64-darwin": "macos-latest",
          "x86_64-linux": "ubuntu-latest",
          "i686-linux": "ubuntu-latest",
          "aarch64-linux": "ubuntu-24.04-arm"
        }
    permissions:
      id-token: write
      contents: read
